'use strict';
let csrf='',previousState='';
const byId=id=>document.getElementById(id),notify=text=>{byId('notice').textContent=text;};
function element(tag,text){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;}
function metrics(root,display,fields){if(!root.dataset.built){root.replaceChildren();for(const[key,label]of Object.entries(fields)){const wrap=element('div');wrap.className='metric';const value=element('strong');value.dataset.metric=key;wrap.append(element('small',label),value);root.append(wrap);}root.dataset.built='yes';}for(const node of root.querySelectorAll('[data-metric]'))node.textContent=display[node.dataset.metric]||'Показания недоступны';}
function offline(){byId('badge').textContent='Нет свежих данных';for(const node of document.querySelectorAll('[data-metric]'))node.textContent='Показания недоступны';notify('Связь с панелью прервана. Ждём восстановления HA.');}
async function api(path,data){const response=await fetch(path,data===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});if(!response.ok)throw new Error(response.status===403?'Откройте панель через HA под разрешённым администратором.':response.status===409?'Другая операция ещё выполняется. Дождитесь завершения.':'Не удалось начать действие. Проверьте код и обновите панель.');return response;}
async function refresh(){const state=await(await api('api/state')).json();csrf=state.csrf;const p=state.presentation||{};byId('status').textContent=state.message||'Не подключён';byId('badge').textContent=state.busy?'Подготовка':p.status||'Нет свежих данных';byId('access').textContent='Доступ: '+(p.access||'Нет данных');metrics(byId('telemetry'),p,{rtt:'Время отклика',receive_rate:'Приём',send_rate:'Передача'});metrics(byId('traffic'),p,{received:'Получено',sent:'Отправлено',total:'Всего'});byId('updated').textContent=p.updated||'Время обновления неизвестно';byId('since').textContent='Статистика с: '+(p.statistics_since||'Нет данных');byId('mqtt-status').textContent=state.mqtt?.state==='connected'?'Сущности доступны в Home Assistant.':'Для сущностей подключите MQTT и Mosquitto broker на этом HA.';byId('setup').hidden=state.configured;byId('rebind-section').hidden=!state.configured;byId('other-section').hidden=!state.configured;if(state.state==='revoked'){byId('rebind-title').textContent='Восстановить подключение';byId('rebind-message').textContent='Доступ отозван. Получите новый код этого подключения на Server и вставьте сюда. Повторная установка Client и подготовка HA не нужны.';if(previousState!=='revoked')byId('rebind-section').open=true;}else{byId('rebind-title').textContent='Заменить код подключения';byId('rebind-message').textContent='Получите новый код того же подключения. Адрес и настройки HA сохранятся.';}previousState=state.state;for(const id of ['connect-button','retry','rebind-button','other-button'])byId(id).disabled=state.busy;byId('retry-section').hidden=!state.configured||['connected','confirm_http','paused','expired','revoked','clock_error'].includes(state.state);byId('confirm-http').hidden=state.state!=='confirm_http';byId('address').hidden=!state.domain;if(state.domain){byId('address').href='https://'+state.domain;byId('address').textContent='https://'+state.domain;}}
async function connect(invitation){await api('api/connect',{invitation});byId('invitation').value='';notify('Подготовка запущена. При перезапуске HA связь с панелью может прерваться.');await refresh();}
byId('connect').addEventListener('submit',async event=>{event.preventDefault();byId('connect-button').disabled=true;try{await connect(byId('invitation').value.trim());}catch(e){notify(e.message);}finally{byId('connect-button').disabled=false;}});byId('retry').addEventListener('click',()=>connect(null).catch(e=>notify(e.message)));
byId('rebind').addEventListener('submit',async event=>{event.preventDefault();byId('rebind-button').disabled=true;try{await api('api/rebind',{invitation:byId('replacement').value.trim()});byId('replacement').value='';notify('Проверяем новый код. При ошибке прежняя привязка сохранится.');await refresh();}catch(e){notify(e.message);}finally{byId('rebind-button').disabled=false;}});
byId('other').addEventListener('submit',async event=>{event.preventDefault();if(!byId('other-confirmed').checked||!confirm('Заменить текущую привязку новым подключением?'))return;byId('other-button').disabled=true;try{await api('api/replace-connection',{invitation:byId('other-code').value.trim(),confirmed:true});byId('other-code').value='';byId('other-confirmed').checked=false;notify('Проверяем новое подключение. При ошибке кода прежняя привязка сохранится.');await refresh();}catch(e){notify(e.message);}finally{byId('other-button').disabled=false;}});
byId('help').addEventListener('toggle',async()=>{if(!byId('help').open||byId('help-content').dataset.loaded)return;try{const result=await(await api('api/help')).json(),root=byId('help-content');root.replaceChildren();renderInstruction(root,result.text);root.dataset.loaded='yes';}catch(e){notify(e.message);}});
refresh().catch(offline);setInterval(()=>refresh().catch(offline),5000);
function renderInstruction(root,text){root.replaceChildren();let table=null;function inline(parent,line){const pattern=/\[([^\]]+)\]\(([^)]+)\)/g;let start=0,match;while((match=pattern.exec(line))){parent.append(document.createTextNode(line.slice(start,match.index).replace(/\*\*|`/g,'')));const target=match[2];if(target.startsWith('https://')){const link=element('a',match[1]);link.href=target;link.target='_blank';link.rel='noopener noreferrer';parent.append(link);}else parent.append(document.createTextNode(match[1]));start=pattern.lastIndex;}parent.append(document.createTextNode(line.slice(start).replace(/\*\*|`/g,'')));}for(const raw of text.split('\n')){const line=raw.trim();if(!line)continue;if(line.startsWith('|')){if(/^\|[\s:|\-]+\|$/.test(line))continue;if(!table){table=element('table');root.append(table);}const row=element('tr');for(const cell of line.slice(1,-1).split('|')){const td=element('td');inline(td,cell.trim());row.append(td);}table.append(row);continue;}table=null;const node=element(line.startsWith('#')?'h3':'p');inline(node,line.replace(/^#{1,3} /,'').replace(/^- /,'• '));root.append(node);}}