name: HA Tunnel Server
version: "0.3.2"
slug: ha_tunnel_server
description: Собственный сервер защищённого удалённого доступа к Home Assistant
arch: [amd64]
image: ghcr.io/stepan-fair/ha-tunnel-server-{arch}
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_admin: true
panel_icon: mdi:server-security
services: [mqtt:want]
homeassistant_api: true
hassio_api: true
hassio_role: default
ports:
  7000/tcp: 7000
ports_description:
  7000/tcp: Защищённые подключения клиентов
options:
  base_domain: ""
  server_url: ""
  npm_host: ""
  admin_user_ids: []
  reserved_names: []
  bandwidth_limit_mb: 10
schema:
  base_domain: str
  server_url: str
  npm_host: str
  admin_user_ids: [str]
  reserved_names: [str]
  bandwidth_limit_mb: int(1,1000)
