'use strict';
let csrf='',currentTab='connections',setupState=null,journalCursor=null,journalZone='UTC',refreshing=false;
const cards=new Map(),byId=id=>document.getElementById(id);
const notify=text=>{byId('notice').textContent=text;};
const date=(value,zone=journalZone)=>value==null?'Нет данных':new Date(value*1000).toLocaleString('ru-RU',{timeZone:zone})+' ('+zone+')';
const accessNames={allowed:'Доступ открыт',paused:'На паузе',expired:'Срок доступа истёк',revoked:'Доступ отозван',pending:'Ожидает подключения',clock_error:'Проверка времени сервера'};
function element(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
async function api(path,data){const response=await fetch(path,data===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});if(!response.ok){let info={};try{info=await response.json();}catch{}throw new Error(info.message||(response.status===409?'Настройки изменились. Обновите данные и повторите.':response.status===403?'Нет доступа. Откройте панель через HA под разрешённым администратором.':'Операция не выполнена. Проверьте данные и состояние сервера.'));}return response;}
function button(parent,text,handler,cls='secondary'){const node=element('button',text,cls);node.type='button';node.addEventListener('click',async()=>{if(node.dataset.busy)return;node.dataset.busy='yes';node.disabled=true;try{await handler();}catch(e){notify(e.message);}finally{delete node.dataset.busy;node.disabled=false;}});parent.append(node);return node;}
function showCode(result){byId('code').value=result.invitation;byId('new-domain').textContent=result.domain+' · действует до '+date(result.expires);if(!byId('code-dialog').open)byId('code-dialog').showModal();}
function showTab(tab){currentTab=tab;document.querySelectorAll('.panel').forEach(node=>node.hidden=node.id!==tab);document.querySelectorAll('[data-tab]').forEach(node=>node.setAttribute('aria-selected',String(node.dataset.tab===tab)));if(tab==='journal')loadJournal(false).catch(e=>notify(e.message));if(tab==='settings')loadSettings().catch(e=>notify(e.message));if(tab==='help')loadHelp().catch(e=>notify(e.message));}
document.querySelectorAll('[data-tab]').forEach(node=>node.addEventListener('click',()=>showTab(node.dataset.tab)));
function makeCard(client){const card=element('article',undefined,'client');card.dataset.id=client.id;card._client=client;const top=element('div',undefined,'card-top'),info=element('div');const link=element('a',client.domain,'domain');link.href='https://'+client.domain;link.target='_blank';link.rel='noopener noreferrer';const status=element('p','','status'),deadline=element('p','','brief');info.append(link,status,deadline);top.append(info);card.append(top);const path='api/clients/'+encodeURIComponent(client.id);
 const change=async(action,duration,timezone)=>{const latest=card._client;try{await api(path+'/access',{action,command_id:commandId(),revision:latest.revision,duration,timezone});notify('Доступ изменён.');}finally{await refresh();}};
 const toggle=button(top,'Пауза',()=>change(card._client.access_state==='allowed'?'pause':'start'),'');
 const brief=element('p','','brief');card.append(brief);
 const details=element('details'),summary=element('summary','Подробности и управление');details.append(summary);card.append(details);
 const metrics=element('div',undefined,'metrics'),values={};for(const[key,label]of Object.entries({rtt:'Время отклика',receive_rate:'Приём',send_rate:'Передача',received:'Получено',sent:'Отправлено',total:'Всего'})){const wrap=element('div',undefined,'metric'),value=element('strong');wrap.append(element('small',label),value);values[key]=value;metrics.append(wrap);}details.append(metrics);const updated=element('p','','hint'),since=element('p','','hint');details.append(updated,since,element('p','Приём и передача — со стороны Client. Трафик включает проверки связи; шифрование транспорта не учитывается.','hint'));
 const controls=element('div',undefined,'controls');details.append(controls);button(controls,'Показать код',async()=>showCode(await(await api(path+'/invitation/show',{})).json()));button(controls,'Выдать новый код',async()=>{showCode(await(await api(path+'/invitation/reissue',{})).json());notify('Введите код в Client этого подключения.');});const revoke=button(controls,'Отозвать доступ',async()=>{if(!confirm('Отозвать доступ для '+card._client.domain+'? Соединения закроются, запись перейдёт в «Отозванные».'))return;await api(path+'/revoke',{});await refresh();},'danger');const remove=button(controls,'Удалить окончательно',async()=>{const c=card._client;const typed=prompt('Чтобы навсегда удалить подключение и освободить адрес, введите домен: '+c.domain);if(typed!==c.domain)return;await api(path+'/delete',{revision:c.revision,confirm_domain:typed});await refresh();},'danger');
 const durationDetails=element('details');durationDetails.append(element('summary','Изменить срок доступа'));details.append(durationDetails);const form=element('form',undefined,'duration'),fields=element('div',undefined,'duration-fields'),inputs={};form.append(fields);durationDetails.append(form);
 for(const[key,label]of Object.entries({years:'Лет',months:'Месяцев',weeks:'Недель',days:'Дней',hours:'Часов',minutes:'Минут'})){const wrap=element('label',label),input=element('input');input.type='number';input.min='0';input.max='9999';input.step='1';input.value=client.duration?.[key]||0;input.name=key;wrap.append(input);fields.append(wrap);inputs[key]=input;}
 const zoneLabel=element('label','Часовой пояс срока'),zone=element('input');zone.value=client.timezone==='UTC'?journalZone:client.timezone||journalZone;zoneLabel.append(zone);form.append(zoneLabel);const preview=element('p','Срок начинается при сохранении. Пуск после истечения повторяет его; ручная пауза не сдвигает дату.','hint');form.append(preview);const valuesOf=()=>Object.fromEntries(Object.entries(inputs).map(([key,input])=>[key,Number(input.value)]));let timer,serial=0;
 form.addEventListener('input',()=>{clearTimeout(timer);const request=++serial;timer=setTimeout(async()=>{try{const p=await(await api('api/duration/preview',{duration:valuesOf(),timezone:zone.value})).json();if(request===serial&&form.isConnected)preview.textContent='Если сохранить сейчас: до '+date(p.deadline,p.timezone);}catch{if(request===serial)preview.textContent='Укажите положительный срок и действующий часовой пояс.';}},400);});
 const presets=element('div',undefined,'controls');form.append(presets);for(const[label,value]of [['20 минут',{minutes:20}],['1 час',{hours:1}],['1 день',{days:1}],['1 неделя',{weeks:1}],['1 месяц',{months:1}],['1 год',{years:1}]])button(presets,label,()=>{for(const[key,input]of Object.entries(inputs))input.value=value[key]||0;form.dispatchEvent(new Event('input'));});const actions=element('div',undefined,'controls');form.append(actions);const save=element('button','Сохранить и запустить');save.type='submit';actions.append(save);button(actions,'Бессрочно',()=>change('permanent'));form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;try{await change('set_duration',valuesOf(),zone.value);}catch(e){notify(e.message);}finally{save.disabled=false;}});
 card.update=c=>{card._client=c;const p=c.presentation||{};status.textContent=accessNames[c.access_state]||'Нет данных';deadline.textContent='Доступ: '+(p.access||'Нет данных');brief.textContent=(p.status||'Показания недоступны')+' · Приём '+(p.receive_rate||'—')+' · Передача '+(p.send_rate||'—');for(const[key,node]of Object.entries(values))node.textContent=p[key]||'Нет данных';updated.textContent=p.updated||'Время обновления неизвестно';since.textContent='Статистика с: '+(p.statistics_since||'Нет данных');toggle.hidden=c.revoked;toggle.textContent=c.access_state==='allowed'?'Пауза':'Пуск';toggle.disabled=!!toggle.dataset.busy||!c.editable||!c.enrolled;remove.hidden=!c.revoked;revoke.hidden=c.revoked;durationDetails.hidden=c.revoked||!c.enrolled||!c.editable;};card.update(client);return card;}
function reconcile(clients,archived){const seen=new Set();for(const[cset,root]of [[clients,byId('clients')],[archived,byId('archived-clients')]]){for(const client of cset){seen.add(client.id);let card=cards.get(client.id);if(!card){card=makeCard(client);cards.set(client.id,card);}card.update(client);if(card.parentNode!==root)root.append(card);}}for(const[id,card]of cards)if(!seen.has(id)){card.remove();cards.delete(id);}byId('archive-count').textContent='('+archived.length+')';byId('archive').hidden=!archived.length;if(!clients.length&&!byId('clients').querySelector('.empty'))byId('clients').append(element('p','Нет активных подключений. Создайте код для нового дома.','empty'));if(clients.length)byId('clients').querySelector('.empty')?.remove();}
async function refresh(){if(refreshing)return;refreshing=true;try{const data=await(await api('api/state')).json();csrf=data.csrf;if(!Array.isArray(data.clients)){setupState=data;journalZone=data.detected?.timezone||'UTC';document.querySelector('[data-tab="connections"]').disabled=true;document.querySelector('[data-tab="journal"]').disabled=true;showTab(currentTab==='help'?'help':'settings');fillSettings(data);return;}journalZone=data.timezone||data.clients[0]?.presentation?.timezone||journalZone;reconcile(data.clients,data.archived||[]);byId('mqtt-status').textContent=data.mqtt?.state==='connected'?'Сущности доступны в Home Assistant.':'Для сущностей подключите MQTT и Mosquitto broker на этом HA.';}finally{refreshing=false;}}
function offline(){notify('Панель временно недоступна. Ждём восстановления связи.');for(const card of cards.values()){card.querySelector('.brief').textContent='Показания недоступны';}}
function fillSettings(data){if(byId('settings-form').dataset.loaded)return;setupState=data;csrf=data.csrf||csrf;const o=data.options||{},d=data.detected||{};journalZone=d.timezone||journalZone;byId('base-domain').value=o.base_domain||'';byId('server-url').value=o.server_url||'';byId('npm-host').value=o.npm_host||d.npm_host||'';byId('admin-users').value=(o.admin_user_ids?.length?o.admin_user_ids:[data.user_id].filter(Boolean)).join('\n');byId('reserved').value=(o.reserved_names||[]).join(', ');byId('bandwidth').value=o.bandwidth_limit_mb||10;byId('settings-title').textContent=data.ready?'Настройка сервера':'Первый запуск сервера';byId('settings-status').textContent=(data.ready?'Настройки действующей установки.':'Пока работают только мастер и проверка состояния. Укажите домен и подготовьте DNS/NPM по инструкции.')+' Часовой пояс: '+journalZone+'.'+(d.startup_problem?' '+d.startup_problem:'');byId('server-host').textContent='Внутреннее имя Server для NPM: '+(d.server_host||'не удалось определить')+' · Архитектура: '+(d.arch||'не определена');byId('settings-form').dataset.loaded='yes';}
async function loadSettings(){if(byId('settings-form').dataset.loaded)return;fillSettings(await(await api('api/setup')).json());}
byId('settings-form').addEventListener('submit',async event=>{event.preventDefault();const node=byId('save-settings');node.disabled=true;try{const draft={base_domain:byId('base-domain').value.trim().toLowerCase(),server_url:byId('server-url').value.trim(),npm_host:byId('npm-host').value.trim(),admin_user_ids:byId('admin-users').value.split(/[\s,]+/).filter(Boolean),reserved_names:byId('reserved').value.split(/[\s,]+/).filter(Boolean),bandwidth_limit_mb:Number(byId('bandwidth').value)};await api('api/setup',{draft,revision:setupState.revision});notify('Настройки сохранены. Server перезапускается; обновите страницу после запуска.');}catch(e){notify(e.message+' При конфликте обновите страницу, предварительно сохранив введённые значения.');}finally{node.disabled=false;}});
byId('network-form').addEventListener('submit',async event=>{event.preventDefault();const node=byId('check-network');node.disabled=true;try{const result=await(await api('api/setup/check',{server_url:byId('server-url').value.trim(),wan_ip:byId('wan-ip').value.trim()||null,static_confirmed:byId('static-confirmed').checked,skip_external:!byId('external-check').checked})).json();const root=byId('network-results');root.replaceChildren();for(const[key,label]of Object.entries({wan:'WAN роутера',static:'Постоянный IP',external:'Внешний IP',dns:'DNS',tls:'HTTPS'})){const c=result[key],p=element('p');p.append(element('strong',label+': '),element('span',({ok:'Подтверждено',problem:'Требует исправления',unknown:'Не подтверждено'}[c.status])+' · '+c.message+(c.ip?' '+c.ip:'')));root.append(p);}}catch(e){notify(e.message);}finally{node.disabled=false;}});
const eventNames={issue:'Создан код подключения',show_code:'Показан код',reissue:'Выдан новый код',redeem:'Код использован',revoke:'Доступ отозван',delete:'Подключение удалено',pause:'Доступ приостановлен',start:'Доступ возобновлён',set_duration:'Изменён срок доступа',permanent:'Бессрочный доступ',expired:'Срок доступа истёк',ha_available:'Изменение доступности HA',frp_connected:'Изменение подключения туннеля',startup:'Server запущен',shutdown:'Server остановлен',unclean_shutdown:'Предыдущая остановка не завершилась',settings:'Настройки сервера',backup_export:'Экспорт копии',backup_restore:'Восстановление копии',operation_failed:'Операция не выполнена',migration:'Обновление состояния'};
function journalQuery(){const q=new URLSearchParams();for(const[name,id]of [['client_id','journal-client'],['action','journal-action'],['result','journal-result']])if(byId(id).value)q.set(name,byId(id).value);for(const[name,id]of [['since','journal-since'],['until','journal-until']])if(byId(id).value)q.set(name+'_day',byId(id).value);return q;}
async function journalCatalog(){const data=await(await api('api/journal/meta')).json();function select(id,items){const node=byId(id),previous=node.value;node.replaceChildren(node.options[0]);for(const[value,label]of items){const option=element('option',label);option.value=value;node.append(option);}node.value=previous;}select('journal-client',data.clients.map(c=>[c.client_id,c.domain+' · '+c.client_id.slice(-8)+(c.deleted?' · удалено':c.revoked?' · отозвано':'')]));select('journal-action',[...new Set([...Object.keys(eventNames),...data.actions])].map(action=>[action,eventNames[action]||'Действие: '+action]));const bytes=data.estimated_bytes,unit=bytes>=1000000?'МБ':bytes>=1000?'КБ':'Б',div=bytes>=1000000?1000000:bytes>=1000?1000:1;byId('journal-size').textContent='Событий: '+data.events.toLocaleString('ru-RU')+' · Объём истории примерно '+(bytes/div).toLocaleString('ru-RU',{maximumFractionDigits:1})+' '+unit;}
async function loadJournal(more){if(!more)await journalCatalog();const q=journalQuery();if(more&&journalCursor)q.set('before_id',journalCursor);const data=await(await api('api/journal?'+q)).json();const root=byId('journal-items');if(!more)root.replaceChildren();if(!data.items.length&&!more)root.append(element('p','Событий по выбранным условиям нет.'));for(const item of data.items){const row=element('article',undefined,'journal-item');const description=eventNames[item.action]||'Действие: '+item.action;row.append(element('strong',description),element('p',date(item.at)+' · '+({success:'Выполнено',requested:'Начато',error:'Ошибка',unknown:'Результат неизвестен'}[item.result]||item.result),'hint'));if(item.domain)row.append(element('p',item.domain));const who={web:'Панель HA',mqtt:'Команда MQTT',client:'Client',timer:'Таймер',system:'Система'}[item.source]||item.source;row.append(element('p',who+(item.user_id?' · пользователь '+item.user_id:'')+(item.details?.available!==undefined?' · '+(item.details.available?'доступно':'недоступно'):''),'hint'));root.append(row);}journalCursor=data.next_cursor;byId('journal-more').hidden=!journalCursor;}
byId('journal-filters').addEventListener('submit',event=>{event.preventDefault();loadJournal(false).catch(e=>notify(e.message));});byId('journal-more').addEventListener('click',()=>loadJournal(true).catch(e=>notify(e.message)));
function download(blob,name){const url=URL.createObjectURL(blob),link=element('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
byId('journal-csv').addEventListener('click',()=>{const link=element('a');link.href='api/journal/export?'+journalQuery();link.download='ha-tunnel-journal.csv';link.click();});
async function loadHelp(){if(byId('help-content').dataset.loaded)return;const result=await(await api('api/help')).json();const root=byId('help-content');root.replaceChildren();renderInstruction(root,result.text);root.dataset.loaded='yes';}
byId('create').addEventListener('submit',async event=>{event.preventDefault();const node=event.submitter;node.disabled=true;try{showCode(await(await api('api/clients',{name:byId('name').value.trim()})).json());await refresh();notify('Код создан.');}catch(e){notify(e.message);}finally{node.disabled=false;}});byId('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(byId('code').value);notify('Код скопирован.');}catch{byId('code').select();notify('Код выделен — скопируйте его.');}});byId('close-code').addEventListener('click',()=>{byId('code-dialog').close();byId('code').value='';});byId('code-dialog').addEventListener('close',()=>{byId('code').value='';});byId('refresh').addEventListener('click',()=>refresh().catch(offline));
byId('export').addEventListener('click',async()=>{try{download(await(await api('api/backup/export',{password:byId('backup-password').value})).blob(),'ha-tunnel.hatb');byId('backup-password').value='';notify('Зашифрованная копия подготовлена.');}catch(e){notify(e.message);}});
byId('restore').addEventListener('click',async()=>{try{const file=byId('backup-file').files[0];if(!file||file.size>10*1024*1024)throw new Error('Выберите файл копии до 10 МиБ.');if(!confirm('Восстановить историю и подключения на пустом сервере? Старые ключи и коды перестанут действовать. После восстановления выдайте новые коды в разделе «Отозванные».'))return;const backup=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await api('api/backup/restore',{password:byId('backup-password').value,backup});byId('backup-password').value='';notify('Копия принята. После перезапуска выдайте новые коды в разделе «Отозванные».');}catch(e){notify(e.message);}});
refresh().catch(offline);setInterval(()=>refresh().catch(offline),15000);
function renderInstruction(root,text){root.replaceChildren();let table=null;function inline(parent,line){const pattern=/\[([^\]]+)\]\(([^)]+)\)/g;let start=0,match;while((match=pattern.exec(line))){parent.append(document.createTextNode(line.slice(start,match.index).replace(/\*\*|`/g,'')));const target=match[2];if(target.startsWith('https://')){const link=element('a',match[1]);link.href=target;link.target='_blank';link.rel='noopener noreferrer';parent.append(link);}else parent.append(document.createTextNode(match[1]));start=pattern.lastIndex;}parent.append(document.createTextNode(line.slice(start).replace(/\*\*|`/g,'')));}for(const raw of text.split('\n')){const line=raw.trim();if(!line)continue;if(line.startsWith('|')){if(/^\|[\s:|\-]+\|$/.test(line))continue;if(!table){table=element('table');root.append(table);}const row=element('tr');for(const cell of line.slice(1,-1).split('|')){const td=element('td');inline(td,cell.trim());row.append(td);}table.append(row);continue;}table=null;const node=element(line.startsWith('#')?'h3':'p');inline(node,line.replace(/^#{1,3} /,'').replace(/^- /,'• '));root.append(node);}}
